# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gurunavi 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "gurunavi".freeze
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["kobayang".freeze]
  s.date = "2017-02-03"
  s.description = "A Gurunavi API wrapper of ruby gems".freeze
  s.email = "naokiod@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "test/helper.rb"
  ]
  s.homepage = "http://github.com/kobayang/gurunavi".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.5.2".freeze
  s.summary = "A Gurunavi API wrapper of ruby gems".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<faraday>.freeze, ["~> 0.8"])
      s.add_development_dependency(%q<faraday_middleware>.freeze, [">= 0.8"])
      s.add_development_dependency(%q<hashie>.freeze, ["< 4.0.0", ">= 0.8"])
      s.add_development_dependency(%q<test-unit>.freeze, ["~> 3.0"])
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.3"])
      s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.13.0"])
      s.add_development_dependency(%q<jnunemaker-matchy>.freeze, [">= 0.0"])
      s.add_development_dependency(%q<fakeweb>.freeze, ["~> 1.3"])
      s.add_development_dependency(%q<awesome_print>.freeze, [">= 0"])
      s.add_development_dependency(%q<mocha>.freeze, [">= 0"])
    else
      s.add_dependency(%q<faraday>.freeze, ["~> 0.8"])
      s.add_dependency(%q<faraday_middleware>.freeze, [">= 0.8"])
      s.add_dependency(%q<hashie>.freeze, ["< 4.0.0", ">= 0.8"])
      s.add_dependency(%q<test-unit>.freeze, ["~> 3.0"])
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.3"])
      s.add_dependency(%q<simplecov>.freeze, ["~> 0.13.0"])
      s.add_dependency(%q<jnunemaker-matchy>.freeze, [">= 0.0"])
      s.add_dependency(%q<fakeweb>.freeze, ["~> 1.3"])
      s.add_dependency(%q<awesome_print>.freeze, [">= 0"])
      s.add_dependency(%q<mocha>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<faraday>.freeze, ["~> 0.8"])
    s.add_dependency(%q<faraday_middleware>.freeze, [">= 0.8"])
    s.add_dependency(%q<hashie>.freeze, ["< 4.0.0", ">= 0.8"])
    s.add_dependency(%q<test-unit>.freeze, ["~> 3.0"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.3"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0.13.0"])
    s.add_dependency(%q<jnunemaker-matchy>.freeze, [">= 0.0"])
    s.add_dependency(%q<fakeweb>.freeze, ["~> 1.3"])
    s.add_dependency(%q<awesome_print>.freeze, [">= 0"])
    s.add_dependency(%q<mocha>.freeze, [">= 0"])
  end
end

